# Generated by Django 4.2.4 on 2023-08-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_question_delete_person_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_real',
            field=models.BooleanField(default=True),
        ),
    ]
